### PR TITLE
Backend : Added code for consuming JD and Resume

### PR DESCRIPTION
**Pull request by KarthikBalajiB**
1) Added REST API's to consume Job Description from the frontend.
2) Modified the existing code to consume resume from static to retrieve from the frontend.
3) The frontend can directly integrate with the backend with just calling the API's. CORS were handled.

TBD:

1) Once Models code is refactored , it can be integrated and can be hosted as api for the frontend to consume and display.
(Display Score , Download Updated Resume as PDF/DOC)

### CODE REVIEW

**Review by pktpaulie — APPROVED** [review]
image

flask_cors is missing in requirements.txt

**Comment by KarthikBalajiB** [comment]
> image
> 
> flask_cors is missing in requirements.txt

Thanks for pointing out. Added it in requirements.txt and updated the PR.

**Review by anushkabhatcode — APPROVED** [review]

**Review by Kavyan17 — APPROVED** [review]
Thanks Karthik. Will start with the Frontend integration based on the API's you developed.

**Review by Anjalipolasani — APPROVED** [review]
looks good!

**Pull request merged**
