### PR TITLE
Add gemeni pro

### PR DESCRIPTION
**Pull request by anushkabhatcode**
I am exploring gemeni pro to do the resume scoring as we are going to be using gemeni pro for resume generation.
 1. I am still testing this with bunch of resumes to see if the scoring is consistent and relevant.
 2. Making changes to the prompts to get better results.
 Though this is a pretty basic version , I am making this commit so that this is present when backend is hosted.

### CODE REVIEW

**Review by pktpaulie — APPROVED** [review]
Great job! The score after tailoring is encouraging - shows improvement in the file and fitness. 

I think import os is repeated and datetime is not being used. 

Result shown below was before tailoring and job description was for data analysis: the reasoning from the model is very helpful and adds completeness to the Job Matching

image

**Review by Anjalipolasani — APPROVED** [review]
Great changes @anushkabhatcode

**Comment by anushkabhatcode** [comment]
I have ipynb so that its easier for everyone to test. Will continue to make changes to .py

**Review by Kavyan17 — APPROVED** [review]
Good progress.

**Review by KarthikBalajiB — APPROVED** [review]
Good Improvement in Scoring and the addition of the reasoning feature.

**Pull request merged**
