### PR TITLE
Add Streamlit App Implementation

### PR DESCRIPTION
**Pull request by pktpaulie**
Anushka and I created a streamlit app showing the barebones functionality of ResumeMagic.

You can test the deployed app on hugging face [here](https://huggingface.co/spaces/pktpaulie/resumeMagic)

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]

**Comment by Kavyan17** [comment]
@pktpaulie, What about the front-end and back-end build that's currently on-going? 
Are we discarding whatever built so far?

**Review by KarthikBalajiB — COMMENTED** [review]
I can see a different app.py in streamlit which is different from what I pushed.
Are we going with this version instead and is this the final version of the product?

**Comment by anushkabhatcode** [comment]
@Kavyan17 @KarthikBalajiB Nobody's work will be discarded, we were testing our models on huggingface using streamlit and had created a simple UI in case we had to show demo to Jackie a little bit earlier than when the UI completes. Be assured that your work is very important to us and that is what we intend to use in final presentation and to Jackie. But let's meet today and communicate within the team to address the issue.

**Comment by Kavyan17** [comment]
I appreciate for valuing the work done so far. However, as a team I expect to be communicated about a new work being done. This is a surprise that made me felt I'm working on something which is already done.

**Comment by KarthikBalajiB** [comment]
I understand its for demo purpose. But me and @Kavyan17  were working on integration this weekend completely and we are about to complete integration. If we are showing a different prototype, we would have not rushed and maybe worked on something more useful for the demo.

**Comment by pktpaulie** [comment]
> I understand its for demo purpose. But me and @Kavyan17 were working on integration this weekend completely and we are about to complete integration. If we are showing a different prototype, we would have not rushed and maybe worked on something more useful for the demo.

Its not solely for demo purposes, this benefits all of us as everyone can test any new model development without having to look for an API or running the code in colab since we currently have no CI/CD Pipeline in place. I hope this makes it easier to understand. 

The app.py in Streamlit is totally different from react app.py or flask app.py. Also, Streamlit is limited. I don't think there is anything more or less useful, we are working towards the same goal.

**Review by Kavyan17 — APPROVED** [review]

**Review by KarthikBalajiB — APPROVED** [review]

**Review by Anjalipolasani — APPROVED** [review]
I tested the app great work!

**Pull request merged**
