### PR TITLE
Contact Page Initial Changes

### PR DESCRIPTION
**Pull request by Anjalipolasani**
Created a contact page using react js

### CODE REVIEW

**Review by anushkabhatcode — CHANGES_REQUESTED** [review]
Please add a route for this page so that this page is visible. This is a standalone file.

**Review by pktpaulie — CHANGES_REQUESTED** [review]
Thanks Anushka for mentioning this, the App.jsx page was not edited to include the routing. Line 3 and 11 shown in the screenshot are missing.
Screenshot 2024-10-26 211348

**Review by KarthikBalajiB — COMMENTED** [review]
I cloned the project and tried to run , but it is not rendering contact page. 
Please add the Routes for it be rendered.

**Review by Kavyan17 — COMMENTED** [review]
Please route the page by modifying code in index.js file.

**Comment by zeshengchen** [comment]
@Anjalipolasani Please fix the peer review comments from the group members and move this pull request soon! It looks like that one group member is very nice so that she has provided the solution!

**Comment by zeshengchen** [comment]
@Anjalipolasani Please fix the peer review comments, get it approved by all, and complete it ASAP. Thanks.

**Comment by anushkabhatcode** [comment]
@Anjalipolasani  This PR has been open for a long time , either close this and raise a new one or maybe try to fix this one so that we can see this move forward.

**Comment by zeshengchen** [comment]
@Anjalipolasani Please provide an explanation on closing this pull request. Will you generate another pull request or fixing the peer review comments for this pull request? What is you plan?

**Comment by Anjalipolasani** [comment]
Professor, I'm considering developing the Gemma model to raise a new PR!

**Comment by zeshengchen** [comment]
> Professor, I'm considering developing the Gemma model to raise a new PR!

Please stop by my office hours or talk to me after tomorrow's lecture.

**Pull request closed without merging**
