### PR TITLE
Added Styling and made necessary changes

### PR DESCRIPTION
**Pull request by Kavyan17**
1. Made required changes for index.html.
2. Added pattern.png required for styling, styling pages styles.css and landing page styles.
3. Theme was chosen such that it represents PFW theme(traditional yellow, black and mastadon colors).
4. Made page responsive and animations to make it pleasing.

### CODE REVIEW

**Review by pktpaulie — CHANGES_REQUESTED** [review]
image

Looks really good, great job! 

However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?

**Comment by Kavyan17** [comment]
It was left on purpose as an Error Handling step. If in case the page fails to load in unforeseen circumstances, it would display the Error page. Get Started page is in development and will be routed soon. Hope this clarifies the matter.

> image
> 
> Looks really good, great job!
> 
> However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?

**Comment by pktpaulie** [comment]
> image
> 
> Looks really good, great job!
> 
> However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?

image

The error doesn't look intentional for a user, it's addressing a developer.

**Comment by Kavyan17** [comment]
> > image
> > Looks really good, great job!
> > However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?
> 
> image
> 
> The error doesn't look intentional for a user, it's addressing a developer.

It's a funny way of addressing to a developer. Not intended to users and an Error page to display to Users will be developed. Since, the product is not live, this for now is intended to the team. It is react project's default way of showing an error, which feels little fun to display. However, a re-route can be done if it's causing a concern.

**Comment by KarthikBalajiB** [comment]
> image
> 
> Looks really good, great job!
> 
> However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?

This will again make it look like a error right as the button's functionality is changed? 
Rather, we can have the existing one, which suggests it in developement process and also shows what happens when the page doesn't exist.

**Comment by Kavyan17** [comment]
> > image
> > Looks really good, great job!
> > However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?
> 
> This will again make it look like a error right as the button's functionality is changed? Rather, we can have the existing one, which suggests it in developement process and also shows what happens when the page doesn't exist.

**Comment by pktpaulie** [comment]
> > image
> > Looks really good, great job!
> > However, there is an error when the Get Started button is clicked. Can we route back to the home page for now when its clicked?
> 
> This will again make it look like a error right as the button's functionality is changed? Rather, we can have the existing one, which suggests it in developement process and also shows what happens when the page doesn't exist.

I'm unfamiliar with a button/link not routing being an error during development. You would rather not route it if the page does not exist. This will look like a bug in the presentation if someone asks you to press the button. So the link to the inexistent page could be removed (for now) since its still under development. That's my view. If not just make an empty page with a title Getting Started if you want the button to go somewhere for now.

**Review by pktpaulie — APPROVED** [review]

**Review by anushkabhatcode — APPROVED** [review]

**Review by KarthikBalajiB — APPROVED** [review]

**Review by Anjalipolasani — APPROVED** [review]
The allignment of css ,Html and reactjs  perfectly designed !
great job !

**Pull request merged**
