### PR TITLE
Add Extraction of Education Background Section

### PR DESCRIPTION
**Pull request by pktpaulie**
Add Extraction of Education Background Section Using Bert NER
Update Experience section to check Job Titles using SpaCy 
Formatting of the output file is still WIP

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
I ran the code , and I think for this is really good progress for first iteration of resume text generation.

**Comment by Anjalipolasani** [comment]
it's good

**Review by Anjalipolasani — APPROVED** [review]
great implementation

**Review by Kavyan17 — APPROVED** [review]
Nice work.

**Review by KarthikBalajiB — APPROVED** [review]
Nice work

**Pull request merged**
