### PR TITLE
Styled the resume

### PR DESCRIPTION
**Pull request by anushkabhatcode**
Added styling for resume.

This looks better for me. Planning to see if I can do better than this in coming days. 
I asked the model to give the output in markdown format, from there I identified headings, subheadings etc for the text to look better in the final word document.

### CODE REVIEW

**Review by pktpaulie — APPROVED** [review]
The output looks really good. Great job

**Review by Kavyan17 — APPROVED** [review]
Output format looks better with the new implementation.

**Review by KarthikBalajiB — APPROVED** [review]
The new template looks very good.

**Review by Anjalipolasani — APPROVED** [review]
great work!

**Pull request merged**
