### PR TITLE
Add Resume Improvement using Openai

### PR DESCRIPTION
**Pull request by pktpaulie**
Add Resume Improvement using Openai
GPT-4o-mini tested and improved resume generated
GPT-3.5-turbo results were not good.
Formatting of output still ongoing.

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
Ran the notebook, content is definitely good. Yes, as you mentioned, styling part requires work.

**Review by Anjalipolasani — APPROVED** [review]
great changes!

**Comment by Kavyan17** [comment]
Nice work.
Regarding the bullet points. The following approach is suggested by ChatGPT. If you haven't tried it so far, I suggest trying this approach.

Screenshot 2024-11-01 at 5 24 25 PM

**Review by Kavyan17 — APPROVED** [review]

**Review by KarthikBalajiB — CHANGES_REQUESTED** [review]
Screenshot 2024-11-01 at 5 28 12 PM


Will this only check for BSc and MSc education and what will happen if there is other education?

**Comment by pktpaulie** [comment]
> u haven't tried it so far, I suggest trying t

In my previous code, I wasn't not doing this check for MSc. and BSc, so it was picking everything including a 1 week course I took and a 1 month training I had at an academy. I added this now only to include degrees. Not sure if you run the code before which shows that.

**Comment by pktpaulie** [comment]
> Nice work. Regarding the bullet points. The following approach is suggested by ChatGPT. If you haven't tried it so far, I suggest trying this approach.
> 
> Screenshot 2024-11-01 at 5 24 25 PM

Thanks for the feedback Kavya.

I generated a custom bullet styling with custom spacing after each bullet for the accomplishments, but it was not applying well to the output document, it was also meant to indent the bullets. For now, I have put back the default py docs bullet 'List Bullet' as I figure out why the custom one wasn't working. 

I can explore the manual formatting to add the bullet as you've suggested, but I'll still need to format the spacing between bullets.

**Comment by KarthikBalajiB** [comment]
> > u haven't tried it so far, I suggest trying t
> 
> In my previous code, I wasn't not doing this check for MSc. and BSc, so it was picking everything including a 1 week course I took and a 1 month training I had at an academy. I added this now only to include degrees. Not sure if you run the code before which shows that.

Ya makes sense. But what will happen if the user have other Educational Background other than BSc/MSc?

**Comment by pktpaulie** [comment]
> > > u haven't tried it so far, I suggest trying t
> > 
> > 
> > In my previous code, I wasn't not doing this check for MSc. and BSc, so it was picking everything including a 1 week course I took and a 1 month training I had at an academy. I added this now only to include degrees. Not sure if you run the code before which shows that.
> 
> Ya makes sense. But what will happen if the user have other Educational Background other than BSc/MSc?

Please clarify what exactly you suggested that I should try. 

I have tried several iterations, including not checking specifically what qualification and also making several checks. My previous notebook was making several checks as shown below. 

image

In this commit I removed the extra code cause the goal was to show the output from prompting openai - specifically to match the resume to the job and to accurately extract the different sections of the resume. 

We are exploring Llama and Gema models currently, after which we shall work on styling the output document with Anushka.

**Review by KarthikBalajiB — APPROVED** [review]

**Comment by KarthikBalajiB** [comment]
> > > > u haven't tried it so far, I suggest trying t
> > > 
> > > 
> > > In my previous code, I wasn't not doing this check for MSc. and BSc, so it was picking everything including a 1 week course I took and a 1 month training I had at an academy. I added this now only to include degrees. Not sure if you run the code before which shows that.
> > 
> > 
> > Ya makes sense. But what will happen if the user have other Educational Background other than BSc/MSc?
> 
> Please clarify what exactly you suggested that I should try.
> 
> I have tried several iterations, including not checking specifically what qualification and also making several checks. My previous notebook was making several checks as shown below.
> 
> image
> 
> In this commit I removed the extra code cause the goal was to show the output from prompting openai - specifically to match the resume to the job and to accurately extract the different sections of the resume.
> 
> We are exploring Llama and Gema models currently, after which we shall work on styling the output document with Anushka.

Yes Sounds good.

**Pull request merged**
