### PR TITLE
Backend Phase-3 integration

### PR DESCRIPTION
**Pull request by KarthikBalajiB**
Changes Added:
1) Added the backend code to return the resume as .docx and .pdf to download
2) Commented the API keys that are not required for the execution
3) Refactor the model code to handle cases for both docx and pdf.

For Frontend,

The API can be consumed by calling 
1) /api/downloadresume/pdf
2) /api/downloadresume/docx

For testing the API's, create a file .env in Backend folder and add the below API keys.
GOOGLE_GEMINI_KEY="Your Gemini API Key"
OPENAI_KEY="Your OpenAI API Key"

### CODE REVIEW

**Comment by pktpaulie** [comment]
I am unable to test the code, looks like the requirements.txt was not updated. Most of the dependencies were in the requirements.txt we uploaded in the Streamlit folder. The following were missing, so I installed each apart from exceptions:

1. flask_cors 
2. exceptions - could not install
3. nltk
4. docx
5. docx2txt
6. PyPDF2
7. langchain
8. langchain_community

Couldn't get it to run despite installing them

**Comment by KarthikBalajiB** [comment]
> I am unable to test the code, looks like the requirements.txt was not updated. Most of the dependencies were in the requirements.txt we uploaded in the Streamlit folder. The following were missing, so I installed each apart from exceptions:
> 
> 1. flask_cors
> 2. exceptions - could not install
> 3. nltk
> 4. docx
> 5. docx2txt
> 6. PyPDF2
> 7. langchain
> 8. langchain_community
> 
> Couldn't get it to run despite installing them

Hey @pktpaulie, Thanks for your feedback. 

I didn't change any requirements regarding the model. I just added the requirements needed for the Backend in Backend/requirements.txt.

However there is another requirements.txt in Models folder which you guys created. That has all the dependencies required for the model.

Also you need to have libreoffice installed in your system to check the pdf generation which is same as in the streamlit application.

**Review by anushkabhatcode — APPROVED** [review]

**Review by Kavyan17 — APPROVED** [review]
Works fine.

**Comment by Anjalipolasani** [comment]
Great addition of backend functionality to enable downloading resumes in both .docx and .pdf formats.

**Review by Anjalipolasani — APPROVED** [review]
Great addition of backend functionality to enable downloading resumes in both .docx and .pdf formats.

**Review by pktpaulie — APPROVED** [review]

**Pull request merged**
