### PR TITLE
Added landing page

### PR DESCRIPTION
**Pull request by Kavyan17**
Added React code for landing page which has 

- About 
- Get started

Further development is in progress.

Styling will be added in coming iterations.

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
Great Progress!!

**Review by Anjalipolasani — APPROVED** [review]
looks good

**Review by pktpaulie — APPROVED** [review]
Great work Kavya

**Review by KarthikBalajiB — APPROVED** [review]
Structuring of React components looks clean and good.

**Pull request merged**
