### PR TITLE
Logo added

### PR DESCRIPTION
**Pull request by Kavyan17**
Created Logo required for Front-end of Resume-Builder using ChatGPT 4. The colors are inspired from PFW's theme.

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
Looks good

**Review by pktpaulie — APPROVED** [review]
Nice 👍

**Review by Anjalipolasani — APPROVED** [review]
great

**Review by KarthikBalajiB — APPROVED** [review]
Nice, the colour combination actually resembles PFW colour theme pretty well.

**Pull request merged**
