### PR TITLE
Refined the similarity score code.

### PR DESCRIPTION
**Pull request by anushkabhatcode**
I have deleted the older file for gauging similarity score and added a new one with a different approach which I feel is a good start for this iteration. More changes will come as we get feedback and more exploration.
Here is the approach taken.

Used chatGPT API to extract sections  for experience and skills from both resume and job description.
Preprocessed the text to do some cleaning.
Implemented TF-IDF vectoriser to extract important words from both the documents.
generated the embeddings using SBERT.
Used cosine similiarity to find out the similarity section -wise.
Calculated the final average similarity score.

### CODE REVIEW

**Review by pktpaulie — APPROVED** [review]
There is a great improvement in the results: I get better and more meaningful results of 9% for a job where the resume does not match, and 22.53% for a resume that meets some of the requirements in the job description.

Could you briefly highlight in the PR what the new approach is

**Comment by anushkabhatcode** [comment]
> There is a great improvement in the results: I get better and more meaningful results of 9% for a job where the resume does not match, and 22.53% for a resume that meets some of the requirements in the job description.
> 
> Could you briefly highlight in the PR what the new approach is

Updated the description.

**Review by Kavyan17 — APPROVED** [review]
Good progress.

**Review by KarthikBalajiB — APPROVED** [review]
Good improvisation in the similarity score calculation.

**Review by Anjalipolasani — APPROVED** [review]
great progress

**Pull request merged**
