### PR TITLE
Add Extraction of Experience Section and Generation of Resume Document

### PR DESCRIPTION
**Pull request by pktpaulie**
Currently extract resume from pdf file, getting experience and summarizing it. Tested a pre-trained t5 model to generate a resume with job description but not successful yet. 

Extraction of Education background is still ongoing as well as testing other options for the feature extraction from the job description

The resulting resume is saved to a doc file.

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
Looks promising! Will be helpful in keeping track of the explored models and their usefulness.

**Comment by zeshengchen** [comment]
Please invite all group members to peer review the pull request, by selecting the name at "Reviewers" on top-right location.

**Comment by Kavyan17** [comment]
Great progress on the resume extraction and summarization! Nice work!

**Review by Kavyan17 — APPROVED** [review]

**Review by KarthikBalajiB — APPROVED** [review]
Great progress on extracting experience from resumes.
Excited to see how the T5 model will elevate the generation of Resume with JD.

**Review by Anjalipolasani — APPROVED** [review]
yea,it looks so unique great!

**Pull request merged**
