### PR TITLE
Added code for Get Started Page

### PR DESCRIPTION
**Pull request by Kavyan17**
1. Added code for Get Started Page and Get Started Styling.
2. Additional Styling is in progress.

### CODE REVIEW

**Review by KarthikBalajiB — COMMENTED** [review]
The GetStarting Page looks good. 

Just a suggestion, In the next iteration, can we change some functionalities like get resume score and download resume button will only showup when the JD and Resume is uploaded , so that we can avoid some bugs like when get resume score is clicked without the jd/resume being uploaded.

**Comment by Kavyan17** [comment]
> The GetStarting Page looks good.
> 
> Just a suggestion, In the next iteration, can we change some functionalities like get resume score and download resume button will only showup when the JD and Resume is uploaded , so that we can avoid some bugs like when get resume score is clicked without the jd/resume being uploaded.

Yes, that's a good suggestion. Currently the basic functionalities and integration part is in progress. However, it is a planned feature and it will be added in the upcoming PR's.

**Review by pktpaulie — APPROVED** [review]
Looks good to me

**Review by anushkabhatcode — APPROVED** [review]

**Review by KarthikBalajiB — APPROVED** [review]

**Review by Anjalipolasani — APPROVED** [review]
looks good!

**Pull request merged**
