### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Anjalipolasani**
Created paraphrase-MiniLM-L6-v2 from sentence transformers library which is a pre-trained model
I have tested the resumes with different job descriptions I got the results with the different similarity scores
The one which is irrelevant to Jd with the resume I got 36.35%
The one which is relevant to the Jd and resume I got 73.32 %

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
Great to see you get started! :) I am going to accept this PR. Here are my suggestions for you ahead.
Test with multiple resumes and job descriptions.
Also see if the tailored resume performs better than the untailored one.
Once you have a final refined version, you can convert this into .py and add to repo.

Keep going !

**Review by KarthikBalajiB — APPROVED** [review]
Nice Work Anjali. 

Model is giving good score and the progress looks good so far.

**Review by pktpaulie — APPROVED** [review]
Great job

**Comment by pktpaulie** [comment]
Just one request, kindly place the file inside Models so the repo stays organised

**Review by Kavyan17 — APPROVED** [review]
Great Work. 
The similarity score model is actually giving impressive results.

**Pull request merged**
