### PR TITLE
Display resume in frontend

### PR DESCRIPTION
**Pull request by pktpaulie**
Send resume as json from backend and Display in frontend on button click.

Update requirements file for deployment - included Gunicorn and other dependencies. 

Update models directory location for deployment purposes.

Updated to use new similarity score and resume generation file. 

@zeshengchen this is refactoring the code from everyone

Tailored Resume
image

Score:
image

### CODE REVIEW

**Review by anushkabhatcode — APPROVED** [review]
@pktpaulie I am approving knowing you are going to update the files while this is merging. .

**Review by KarthikBalajiB — COMMENTED** [review]
I cloned this branch and checked and I can see the Download PDF is not working. 
I added this feature in my last PR. 

I think something is missed during this refactoring.

Screenshot 2024-12-05 at 5 34 08 PM

**Comment by pktpaulie** [comment]
> I cloned this branch and checked and I can see the Download PDF is not working. I added this feature in my last PR.
> 
> I think something is missed during this refactoring.
> 
> Screenshot 2024-12-05 at 5 34 08 PM

I indicated that download pdf currently doesnt work in my updated. I have kept the original code there, its simply commented out. The /downloadresume end point used before was sending only the path, I created a new endpoint sending both the filename and the json so that it can be displayed as markdown. 

To avoid querying the resume_generator twice since that will result in 2 different ouputs, I get the path to the generated resume in a different endpoint.

**Comment by KarthikBalajiB** [comment]
> > I cloned this branch and checked and I can see the Download PDF is not working. I added this feature in my last PR.
> > I think something is missed during this refactoring.
> > Screenshot 2024-12-05 at 5 34 08 PM
> 
> I indicated that it doesnt work in my communication to you on the group. Even when I tested it before refactoring it didnt work there was an error in the console, not sure how the rest tested it. I have kept the original code there, its simply commented out. The /downloadresume end point used before was sending only the path, I created a new endpoint sending both the filename and the json so that it can be displayed as markdown.
> 
> To avoid querying the resume_generator twice since that will result in 2 different ouputs, I get the path to the generated resume in a different endpoint.

I hope you remember we showed a demo to the sponsor 2 days back and it perfectly downloaded right in front of her. I don't know how only your machine only faced the issue and you changed the api endpoints of what I developed and now its not working.

The above screenshot is from what the code I pushed actually produced as output.

Screenshot 2024-12-05 at 7 02 28 PM

**Comment by zeshengchen** [comment]
> Send resume as json from backend and Display in frontend on button click.
> 
> Update requirements file for deployment - included Gunicorn and other dependencies.
> 
> Update models directory location for deployment purposes.
> 
> Updated to use new similarity score and resume generation file.
> 
> @zeshengchen this is refactoring the code from everyone
> 
> Tailored Resume image
> 
> Score: image

If the pull request is from everyone, it would be better to allow other group members to commit to this pull request so that it become clear that everyone contributed.

**Comment by anushkabhatcode** [comment]
@zeshengchen We all connected and have reached a same page. Pauline did the refactoring of the code, which is going to help with the deployment. She also worked on displaying the resume in the Front end. The rest of the code is however that of all other team members. I am mentioning this so that it is clear that the code being refactored is the one that was already there except for some changes that felt necessary for integration.

**Review by Anjalipolasani — APPROVED** [review]

**Review by Kavyan17 — APPROVED** [review]

**Review by KarthikBalajiB — APPROVED** [review]

**Pull request merged**
