### PR TITLE
Gemini-pro for text generation

### PR DESCRIPTION
**Pull request by anushkabhatcode**
This notebook is an exploration of Gemini-pro for resume text generation and as of now shows very good potential.

Required Credentials
Google Cloud API Key for the Gemini model in google.generativeai.
Google Service Account JSON Key

I have not included the json file key that is being used in the notebook owing to security reasons.

Pauline will be working on making the prompts better to enhance the quality of the content.

### CODE REVIEW

**Review by pktpaulie — APPROVED** [review]
### **_General Feedback_**
Thank you Anushka, I ran the file and made improvements to the tailor_resume() function to reduce the output to one page and keep most relevant information. 

With the modification, the result looks really good, the summary relates the candidate's skills to the position and maintains the top 3 most relevant accomplishments for each role. 

It's also more efficient than my previous code which made several prompts and several checks to write to the output file. 

We shall need to figure out how to remove the asterisks. 

### **_Modified Function_**
def tailor_resume(resume_text, job_description):
    # Use the generate_resume_text function to get the formatted resume content
    formatted_resume = generate_resume_text(resume_text)
    print("formatted resume:",formatted_resume)
    if formatted_resume:
        prompt = f"""
Below is the candidate's original formatted resume content:

[Resume Start]
{formatted_resume}
[Resume End]

Using the candidate's resume above and the job description below, create a tailored resume.

[Job Description Start]
{job_description}
[Job Description End]

Please generate a resume that:
1. Uses real data from the candidate's resume, including name, and education.
2. Avoids placeholders like "[Your Name]" and includes actual details.
3. In the experience section, emphasizes professional experiences and skills that are directly relevant to the job description.
4. Keeps only a maximum of the top three accomplishments/ responsibilities for each job position held so as to make the candidate standout in the new job role
5. Removes special characters from the section titles
6. Only includes publications if the job description is research based
7. Summarizes the skills and technical skills section into a brief profile
8. Does not include courses, certification, references, skills and a technical skills sections
"""
        try:
            response = model.generate_content(prompt)
            return response.candidates[0].content.parts[0].text
        except Exception as e:
            print("Error in tailoring resume:", e)
            return None
    else:
        return "Failed to generate resume text."

### **_Results_**
This screenshot shows my new resume after inputting a very detailed 2 page CV that includes publications, courses, certifications, referees and a skills section

Screenshot 2024-11-04 222710

**Review by KarthikBalajiB — APPROVED** [review]
The approach of using different models looks good. Waiting to see their efficiency on how it  is going to render details based on the prompts.

**Review by Kavyan17 — APPROVED** [review]
Nice work Anushka. The Gemini Model is a good addition to our models. Looking forward to see the efficiency comparison of both the models.

**Review by Anjalipolasani — APPROVED** [review]
Great work !

**Pull request merged**
